### PR TITLE
add ToC in README.md

### PR DESCRIPTION
**Pull request by sbwww**
Replace underline and hyphen with white space for a better exhibition.

### CODE REVIEW

**Comment by sbwww** [comment]
I'd appreciate it if this repository can be updated, for the sharing of source code is beneficial to us learners.

Hopefully, the README can also be designed with categories if possible (might require much effort).

**Comment by burakbayramli** [comment]
Did you create this TOC with a script? Could you include it here?

**Comment by sbwww** [comment]
> Did you create this TOC with a script? Could you include it here?

Thank you for accepting it.
I regret to say, but that was just Regular Expression and Excel tricks, not involving script or code :stuck_out_tongue_winking_eye:
As it involves problems like special characters in URL, diversity in naming, etc., a script might seem to be complex with my current knowledge.

**Comment by burakbayramli** [comment]
:) Ok that's fine. I'll just have to remember to include new book code subfolders in the TOC then.

**Pull request merged**
